version: '3.8'

services:
  postgres:
    container_name: postgres-local
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: kbtg
      POSTGRES_PASSWORD: kbtg@pass
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
